# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-11 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='spot',
            field=models.CharField(choices=[('center', 'Centro'), ('index', 'Inicio'), ('detail', 'Articulos'), ('hidden', 'Oculta')], default='hidden', max_length=100),
        ),
    ]
