# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-03 15:15
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_auto_20180717_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Contenido'),
        ),
        migrations.AddField(
            model_name='ads',
            name='site_url',
            field=models.CharField(blank=True, max_length=900, null=True, verbose_name='Link'),
        ),
    ]
